server.port: 0
spring:
   security:
      oauth2:
         resourceserver:
            jwt:
               #issuer-uri: http://localhost:8180/auth/realms/micro
               jwk-set-uri: http://localhost:8180/auth/realms/micro/protocol/openid-connect/certs